### ISSUE TITLE
User-defined scripts should have proper names in the User menu

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#322]
**Reported by oliver on 19 Dec 40836581 22:50 UTC**
The commands listed in the "User" menu should have a proper name
(e.g., 'Strip water'  for the 'removeWater()' method). 
An additional column in the corresponding preferences dialog is required, which 
would be displayed instead of the Python command to be executed.

Whether the menu should be named "User" is open to discussion as well. 
The menu doesn't have anything to do with the user, after all.

**Comment by anhi** [comment]
**Commented by dstoeckel on 7 Aug 41343536 01:43 UTC**
This should not block 1.4.1; Removing Milestone

**Comment by tkemmer** [comment]
PyWidget has been deprecated and will be dropped.
