### ISSUE TITLE
python wrapping does not work for nested classes

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#328]
**Reported by akdehof on 17 Oct 40858308 12:31 UTC**
It seems as if sip python wrapping for nested classes is not possible.
This concerns e.g. classes HBondProcessor and NMRStarFile.

**Comment by anhi** [comment]
**Commented by akdehof on 30 Jun 40936093 03:54 UTC**
Deferred to 1.4.1

**Comment by anhi** [comment]
**Commented by dstoeckel on 10 Jul 41152368 11:31 UTC**
In fact we cannot easily solve this without breaking compatibility for sip versions below sip 4.8. Thus we cannot solve this for the 1.4.x series.

**Comment by tkemmer** [comment]
Nested classes should work correctly with currently supported sip versions. Support for sip <4.8 has been dropped as of 20ba64a82c9d9752e1cff75a3fe858b65d25688c.
