### ISSUE TITLE
new FontDialog unconnected

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#347]
**Reported by akdehof on 9 Dec 41075361 13:43 UTC**
TODO: connect

**Comment by anhi** [comment]
**Commented by chahuistle on 26 Feb 44028462 21:57 UTC**
it's not very clear where or how to find the FontDialog

**Comment by tkemmer** [comment]
Removed in 3daea2061a9e645369a43f57ec4b65fccbd6d42a.
