### ISSUE TITLE
BALLView crashes when trying to load the wrong python module

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#348]
**Reported by anhi on 19 Oct 41088227 18:19 UTC**
When BALLView tries to load the wrong python module (e.g., if the PYTHONPATH is wrong), it crashes hard without any hints to the user. We should fix this.

However, this is hard to do: the crash seems to happen when loading the python module overwrites some of the pointers inside BALLView. Maybe we should not load BALL and VIEW through import statements but through the Python C API if that is possible.

**Comment by anhi** [comment]
**Commented by chahuistle on 24 Apr 44028464 03:28 UTC**
since the ''wrong'' python module is being loaded, we'll be treating this as an enhancement

**Comment by tkemmer** [comment]
This should be fixed with the new Python interpreter.
