### ISSUE TITLE
Doxygen documentation needs more fine tune

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#359]
**Reported by akdehof on 29 Oct 41132033 19:18 UTC**
The class documentation on our web page looks strange. For a number of classes the right colum is empty (short description is missing or not correctly parsed...)

**Comment by anhi** [comment]
**Commented by dstoeckel on 24 Mar 41152401 07:07 UTC**
The problem here is that the option to automatically generate a brief class description has been turned off. I suggest to leave it this way and rather add explicit brief descriptions for the classes, as the quality of the generated ones is at best sub-par.

**Comment by tkemmer** [comment]
This is (somewhat) working as intended. For (the never ending issue of) missing documentation, pls refer to #358.
