### ISSUE TITLE
Python scripting mode works like the interactive interpreter

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#386]
**Reported by dstoeckel on 27 Nov 41583542 00:58 UTC**
Currently the contents of the scripting mode window are fed to the interpreter in a line-by-line fashion. This leads to the fact that newlines below blocks (for loops, conditionals, ...) are mandatory.
We should fix this behaviour.

**Comment by tkemmer** [comment]
PyWidget has been deprecated and will be dropped.
