### ISSUE TITLE
Crash in BALLView Python scripting mode

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#387]
**Reported by dstoeckel on 7 Oct 41583546 05:54 UTC**
The following script manages to crash BALLView:

``` python
for i in range(2):
 clearAll()
 name = str(i)
 pdb = PDBFile(Path().find('~/Downloads/foo'+name+'.pdb'))
 S = System()
 pdb.read(S)
 getMainControl().insert(S)
```

This is most likely due to a race condition in our internal messaging system.

**Comment by tkemmer** [comment]
This was actually caused by `clearAll` (or rather, the underlying function in BALL) not respecting `MainControl`'s composite lock. The above script occasionally removed previously added composites while processors were still running on them.
