### ISSUE TITLE
BALLView crashes in RT mode

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#410]
**Reported by nicste on 23 Apr 41970140 22:04 UTC**
After full integration of RTfact code into the master branch (12/2011), BALLView crashes with an undefined symbol error at runtime, when either opening a project in RT mode or switching to RT mode. Seems to come from RTfact. Coould be related to used Boost versions (1.4.0 for BALL/BALLView, 1.4.3 for RTfact)

Detailed error message is:
BALLView: symbol lookup error: /home/AH/nicste/BALL.rtfact/BALL/build/lib/libVIEW.so.1.4: undefined symbol: _ZNKSt3tr14hashIN5boost13intrusive_ptrIN6RTfact6Remote8GeometryEEEEclES6_

**Comment by tkemmer** [comment]
If this issue still occurs with supported Boost versions (1.55+), please open a new ticket.
