### ISSUE TITLE
Unbekannte Modelltypen

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#414]
**Reported by mkonietzko on 24 May 42118007 01:43 UTC**
Bei Ansicht->Display Properties gibt es bei der Modellauswahl viele, fr eine Schulversion, irrefhrende Typen. Bsp. VDW, SES, SAS,... Wobei VDW eventuell interessant sein knnte. Vielleicht bei Schulversion ausschreiben. Stbchen- und Kugelstab-Modell sind am besten geeignet.

**Comment by tkemmer** [comment]
School version has been dropped.
