### ISSUE TITLE
Problem beim Öffnen zweier Projekt

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#424]
**Reported by mkonietzko on 6 Sep 42118242 17:22 UTC**
Wenn ein Projekt geffnet ist und man ffnet ein weiteres wird das alte nicht automatisch geschlossen. In der Schulversion wre es besser wenn das alte Projekt gespeichert und geschlossen wird.

**Comment by tkemmer** [comment]
School version has been dropped. For the regular BALLView version, this behavior is intended.
