### ISSUE TITLE
BALLView crashes on OpenGL rendering on Windows 32Bit

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#440]
**Reported by nicste on 26 Oct 42181592 10:49 UTC**
After the major integration of the Kiosk mode code, BALLView crashes on Windows 32 Bit upon Rendering with OpenGL. Rendering with RTfact is fine.

**Comment by tkemmer** [comment]
Doesn't seem to be a problem anymore. If this issue still occurs in a currently supported environment, please file a new bug.
