### ISSUE TITLE
Fix multilib support on linux

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#444]
**Reported by Justin on 29 Jan 42232838 02:07 UTC**
On multilib installation the correct path for native 64bit libs is the lib64 directory. Please find attached patch for the correct setting in cmake.

**Comment by anhi** [comment]
**Commented by dstoeckel on 30 Aug 42878667 11:00 UTC**
Unfortunately this is not this. My CMake for example does not set this variable. Also most systems install the native libraries into "lib" and libraries that belong to the other architecture into libXX. We need to find a proper way to detect the right directory.

**Comment by anhi** [comment]
**Commented by Justin on 16 Jan 42878735 07:15 UTC**
I am using cmake-2.8.9. I would guess it is supported since 2.8.5, so probably we need to fix CMAKE_MINIMUM_REQUIRED to this.

Regarding lib vs libXX, if you are on a non-multilib system (e.g. x86 or amd64 without 32bit support) everything should be installed into lib. As soon as you have multilib support, you must use libXX to keep things sane. For convenience there might be a symlink "lib64 -> lib" or similar, but this is optional and things need to work without.

**Comment by anhi** [comment]
**Commented by dstoeckel on 15 Apr 42881797 23:43 UTC**
Ok, I found the issue. The variable is defined by the GNUInstallDirs.cmake module, which is only present in cmake 2.8.5 upwards. I do not know if we can already require this version of cmake, so I will make this optional.

The problem is that the distributions differ in what they deem required. Debian based distributions moved to the new scheme of /lib/multiarch_triplet, but still keep lib32 around, whereas lib64 is completely gone (on my 64-bit system).
My Archlinux box does not use the multiarch scheme but uses lib for 64-bit libs and lib32 for 32-bit libs. No lib64 directory is present. Unfortunately the GNUInstallDirs.cmake macro does not account for this ... So the current state can be described as a bloody mess.

So all in all a little bit more thinking will have to go into this :-/

**Comment by tkemmer** [comment]
I'm going to close this one. BALL uses GNUInstallDirs since a8cade5ed7090c704aed53871fb664a0fe07af54. The module - by now - also covers several platform-specific conventions (including /lib/multiarch_triplet) in all versions supported by us. Optionally, directories can still be customized via the respective `CMAKE_INSTALL_*` variables.
