### ISSUE TITLE
RTfactRenderer does not compile with clang

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#464]
**Reported by nicste on 18 Jan 43046128 14:36 UTC**
Compilation with clang (3.0) and boost (1.46) breaks with the following errors:

[ 50%] Built target BALL
[ 50%] Building CXX object CMakeFiles/VIEW.dir/source/VIEW/RENDERING/RENDERERS/rtfactRenderer.o
In file included from /home/AH/nicste/BALL.cmake/source/VIEW/RENDERING/RENDERERS/rtfactRenderer.C:7:
In file included from /home/AH/nicste/BALL.cmake/include/BALL/VIEW/RENDERING/RENDERERS/rtfactRenderer.h:24:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Model/Framebuffer/Image2DFramebuffer.hpp:31:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Concept/Framebuffer.hpp:31:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Vec3f.hpp:32:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Packet.hpp:42:
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/SSEUtils.hpp:226:17: warning: Implement a FTZ/DAZ code for non-Windows systems [messages](-W#pragma)
        #pragma message("Implement a FTZ/DAZ code for non-Windows systems")
                ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/SSEUtils.hpp:732:25: warning: Please check the fastest way for replication [messages](-W#pragma)
                #pragma message "Please check the fastest way for replication"
                        ^
In file included from /home/AH/nicste/BALL.cmake/source/VIEW/RENDERING/RENDERERS/rtfactRenderer.C:7:
In file included from /home/AH/nicste/BALL.cmake/include/BALL/VIEW/RENDERING/RENDERERS/rtfactRenderer.h:24:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Model/Framebuffer/Image2DFramebuffer.hpp:31:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Concept/Framebuffer.hpp:31:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Vec3f.hpp:62:
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Vec3f4.hpp:711:25: warning: Please check the fastest way for replication [messages](-W#pragma)
                #pragma message "Please check the fastest way for replication"
                        ^
In file included from /home/AH/nicste/BALL.cmake/source/VIEW/RENDERING/RENDERERS/rtfactRenderer.C:9:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Config/Init.hpp:35:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.init.hpp:46:
/usr/include/boost/preprocessor/iteration/detail/local.hpp:37:9: error: explicit specialization of 'C_ONE_THIRD' after instantiation
        BOOST_PP_LOCAL_MACRO(1)
        ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.init.hpp:44:35: note: expanded from:
# define  BOOST_PP_LOCAL_MACRO(n)  RTFACT__INIT_CONSTS(n)

```
                              ^
```

/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.init.hpp:41:5: note: expanded from:
    RTFACT_PACKET_INIT_CONSTS(RTFACT_PACKET_SIZE_AT(aIndex))                   \
    ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Packet.hpp:198:5: note: expanded from:
    RTFACT_FLOAT_PACKET_INIT_CONSTS(aSize)                                     \
    ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.hpp:84:44: note: expanded from:
    RTFACT_PACKET_INIT_CONST(aSize, float, C_ONE_THIRD, 0.333333f)             \
                                           ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Packet.hpp:181:73: note: expanded from:
    template<> const Packet<aSize, aBaseType> Packet<aSize, aBaseType>::aName  \
                                                                        ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Vec3f4.hpp:553:43: note: implicit instantiation first required here
        return (x + y + z) \* FloatPacket::C_ONE_THIRD;
                                          ^
In file included from /home/AH/nicste/BALL.cmake/source/VIEW/RENDERING/RENDERERS/rtfactRenderer.C:9:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Config/Init.hpp:35:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.init.hpp:46:
/usr/include/boost/preprocessor/iteration/detail/local.hpp:37:9: error: explicit specialization of 'C_1' after instantiation
        BOOST_PP_LOCAL_MACRO(1)
        ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.init.hpp:44:35: note: expanded from:
# define  BOOST_PP_LOCAL_MACRO(n)  RTFACT__INIT_CONSTS(n)

```
                              ^
```

/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.init.hpp:41:5: note: expanded from:
    RTFACT_PACKET_INIT_CONSTS(RTFACT_PACKET_SIZE_AT(aIndex))                   \
    ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Packet.hpp:199:5: note: expanded from:
    RTFACT_INT_PACKET_INIT_CONSTS(aSize)                                       \
    ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.hpp:98:42: note: expanded from:
    RTFACT_PACKET_INIT_CONST(aSize, int, C_1, 1)                               \
                                         ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Packet.hpp:181:73: note: expanded from:
    template<> const Packet<aSize, aBaseType> Packet<aSize, aBaseType>::aName  \
                                                                        ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Vec3f4.hpp:426:51: note: implicit instantiation first required here
                           (y > z).iif(IntPacket::C_1, IntPacket::C_2));
                                                  ^
In file included from /home/AH/nicste/BALL.cmake/source/VIEW/RENDERING/RENDERERS/rtfactRenderer.C:9:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Config/Init.hpp:35:
In file included from /home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.init.hpp:46:
/usr/include/boost/preprocessor/iteration/detail/local.hpp:37:9: error: explicit specialization of 'C_2' after instantiation
        BOOST_PP_LOCAL_MACRO(1)
        ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.init.hpp:44:35: note: expanded from:
# define  BOOST_PP_LOCAL_MACRO(n)  RTFACT__INIT_CONSTS(n)

```
                              ^
```

/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.init.hpp:41:5: note: expanded from:
    RTFACT_PACKET_INIT_CONSTS(RTFACT_PACKET_SIZE_AT(aIndex))                   \
    ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Packet.hpp:199:5: note: expanded from:
    RTFACT_INT_PACKET_INIT_CONSTS(aSize)                                       \
    ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Constants.hpp:99:42: note: expanded from:
    RTFACT_PACKET_INIT_CONST(aSize, int, C_2, 2)                               \
                                         ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Packet.hpp:181:73: note: expanded from:
    template<> const Packet<aSize, aBaseType> Packet<aSize, aBaseType>::aName  \
                                                                        ^
/home/AH/nicste/uray_nointel/rtfact-anysl/include/RTfact/Utils/Packets/Detail/Vec3f4.hpp:425:69: note: implicit instantiation first required here
        return (x > y).iif((x > z).iif(IntPacket::C_0(), IntPacket::C_2),
                                                                    ^
3 warnings and 3 errors generated.
make[**\* [CMakeFiles/VIEW.dir/source/VIEW/RENDERING/RENDERERS/rtfactRenderer.o](2]:) Error 1
make[**\* [CMakeFiles/VIEW.dir/all](1]:) Error 2
make: **\* [all] Error 2

**Comment by tkemmer** [comment]
This doesn't seem to be a problem any longer with the currently supported toolchain.
