### ISSUE TITLE
Repair and unify Windows NSIS Installers

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#465]
**Reported by dstoeckel on 18 Feb 43068092 14:57 UTC**
There are currently some issues with the NSIS installer:
- It offers to install Python, but declining leads to an inconsistent
  installation if Python 2.7 is not already installed
- There is already a component "Install Python"
- The 32bit Installer lacks a bundled Python installer
- There already are some packaged python files (scons, etc.?).
  What are those good for?

We should fix these issues for a BALL-1.5 release.

**Comment by tkemmer** [comment]
Fixed in current master.
