### ISSUE TITLE
BALLView crashes under Linux on Intel hardware

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#469]
**Reported by dstoeckel on 17 Jan 43139740 19:24 UTC**
BALLView crashes under Ubuntu 12.04 on Intel hardware.
This seems to be a race condition in the OpenGL initialization as sometimes it will start, but produce the output:

```
Mesa 8.0.4 implementation error: meta program compile failed:

source:
#version 130
attribute vec4 position;
void main()
{
   gl_Position = position;
}


Please report at bugs.freedesktop.org
Mesa 8.0.4 implementation error: meta program compile failed:

source:
#version 130
uniform ivec4 color;
out ivec4 out_color;

void main()
{
   out_color = color;
}


Please report at bugs.freedesktop.org
```

Notice the encoding error at the very top.

Here is the ouput of lspci:

```
00:02.0 VGA compatible controller: Intel Corporation Ivy Bridge Graphics Controller (rev 09) (prog-if 00 [controller](VGA))
        Subsystem: Dell Device 052c
        Flags: bus master, fast devsel, latency 0, IRQ 45
        Memory at f7800000 (64-bit, non-prefetchable) [       Memory at e0000000 (64-bit, prefetchable) [size=256M](size=4M]
)
        I/O ports at f000 [       Expansion ROM at <unassigned> [disabled](size=64]
)
        Capabilities: [MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [d0](90]) Power Management version 2
        Capabilities: [a4] PCI Advanced Features
        Kernel driver in use: i915
        Kernel modules: i915
```

The graphics card/cpu is an Intel(R) Core(TM) i7-3770.
The attachment is the output of glxinfo.

**Comment by anhi** [comment]
**Commented by dstoeckel on 11 Jan 43141781 21:49 UTC**
Compiling with 
```
cmake /home/HPL/dstoeckel/source/BALL -DUSE_LPSOLVE=OFF
```
fixes this problem. However valgrind still reports invalid reads and
uninitialized values in Mesa.

Of special interest is the function _mesa_meta_glsl_Clear which likely produced the above
error message and also was the point where BALLView would crash. (According to the attached apitrace)

**Comment by tkemmer** [comment]
Mesa 8 and Ubuntu 12.04 are no longer supported. If this problem still persists in a supported environment, please file a new bug report.
