### ISSUE TITLE
offscreen rendering should give a progress report

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#493]
**Reported by akdehof on 11 Jul 43349744 18:29 UTC**
using the offscreen rendering for generating "large" png (complex molecule and e.g. factor 4) sometimes takes several minutes and thus looks like nothing is happening. 
To avoid this impression a progress feedback 
a) that it actually does something and 
b) if it is finished 
would be very helpful.

**Comment by tkemmer** [comment]
The old off-screen rendering facility is scheduled for deprecation after 1.5.
