### ISSUE TITLE
BALLView unable to ignore nonexisting last_BALL_script.py file locations

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#509]
**Reported by akdehof on 14 Jan 43544588 20:09 UTC**
For some reason I got stuck with a nonexisting file location of 
last_BALL_script.py (I assume it was imported via a ballview project file). Anyhow, I cannot get rid of it. Trying to run a python script always triggers search for that file and yields the annoying error message

loading script from C:\Dokumente und Einstellungen...\last_BALL_script.py

> Could not find file C:\Dokumente und Einstellungen...\last_BALL_script.py

Doing so the python interface of BALLView is unusable :-(

**Comment by anhi** [comment]
**Commented by akdehof on 21 Jul 43544597 10:05 UTC**
The temporary fix is:

locate the BALLView ini file named "./BALLView" in your home directory and manually delete the entry 

[PYTHON]
current_script=C:\\Dokumente und Einstellungen\xxx\last_BALL_script.py

**Comment by tkemmer** [comment]
Also, if the file does exist but is not readable, BALLView refuses to start (or crashes as soon as one tries to run a script, if the file is made unreadable while BALLView is running):
```
---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type Parse Error occurred in line 117 of /home/thomas/git/apps/ball/source/FORMAT/lineBasedFile.C
error message: LineBasedFile::readLine in File '/home/thomas/last_BALL_script.py' not open for reading
---------------------------------------------------
```
