### ISSUE TITLE
Change CommandlineParser to make it compatible with the latest CTD schema

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#510]
**Reported by delagarza on 30 Nov 43714191 23:41 UTC**
The "latest" schema is to be found here: https://github.com/genericworkflownodes/GenericKnimeNodes/blob/develop/com.genericworkflownodes.knime/src/com/genericworkflownodes/knime/schemas/CTD.xsd

**Comment by philthiel** [comment]
Fixed with commits https://github.com/BALL-Project/ball/commit/938661948be04519d23b28e4b1604b2b9c9f73bb, https://github.com/BALL-Project/ball/commit/8ae8010f820656fc062ec933be532deccbf52b3e
