### ISSUE TITLE
Python script "Finished script sucessfully"

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#522]
**Reported by FabianAicheler on 12 Jul 44026502 11:10 UTC**
If a Python script is executed in BallView without errors, the message which is written into the Log is 
"Finished script sucessfully"

Obviously this should be "Finished script successfully"

**Comment by anhi** [comment]
**Commented by chahuistle on 31 Oct 44028561 01:01 UTC**
this shouldn't take much time to fix ;)

**Comment by tkemmer** [comment]
Fixed in ff5d2c20dca960cf9de2f2618d578d85a1cff297.
