### ISSUE TITLE
set origin in VRML export

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#526]
**Reported by mit 24 on 23 Jan 44117242 08:55 UTC**
The centres of coordinates in a scene and VRML file made from it are not the same. I would like them to match each other. Is it possible to set a centre of coordinates when generating VRML ? I haven't found the way.

**Comment by tkemmer** [comment]
VRML support has been dropped in 773c3b69ce74b76fbdc4620fd43d63ad269df732.
