### ISSUE TITLE
CADDSuite generates outdated CTDs

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#528]
**Reported by delagarza on 10 Nov 44258980 06:06 UTC**
All CTD enabled tools (i.e., CADDSuite tools) generate CTDs with an outdated schema. 

The latest schema can be found under https://github.com/genericworkflownodes/GenericKnimeNodes/blob/develop/com.genericworkflownodes.knime.config/src/com/genericworkflownodes/knime/schemas/CTD.xsd

**Comment by chahuistle** [comment]
Fixed with commits https://github.com/BALL-Project/ball/commit/938661948be04519d23b28e4b1604b2b9c9f73bb, https://github.com/BALL-Project/ball/commit/8ae8010f820656fc062ec933be532deccbf52b3e
