### ISSUE TITLE
Error duing build

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#530]
**Reported by Jadzia on 2 Aug 44581946 07:16 UTC**
I get an error every time I compile your package: I attached the build log. 

I was not able to solve this problem. Do you know what the cause of it could be?

**Comment by anhi** [comment]
**Commented by Jadzia on 14 Dec 44581952 00:10 UTC**
I think your attachment system is broken. 
I pasted the log file...
http://bpaste.net/show/532118/

**Comment by philthiel** [comment]
Link is dead. I assume nobody has stored this logfile (or is unable to find it ; ).
So I will close this issue.
