### ISSUE TITLE
Failed compilation on Ubuntu 14

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#532]
**Reported by gkamath on 29 Mar 44678340 03:30 UTC**
Hi ,

I downloaded ball version 1.4.2 and am trying to compile the source. I have built all the
libraries in the contrib.
I can successfully make cmake to work and build the dependencies and configure.

However make results in this error.

make[*** [CMakeFiles/BALL.dir/source/CONCEPT/moleculeObjectCreator.o](2]:) Error 1
make[*** [CMakeFiles/BALL.dir/all](1]:) Error 2
make: *** [all] Error 2

Could you please help?

thanks,
ganesh kamath

**Comment by smoe** [comment]
We have a Debian package of BALL in the distribution and there are also Ubuntu packages. You find some on https://launchpad.net/ubuntu/+source/ball . You may decide to recompile those packages and please also inspect the build dependencies.  @anhi had no further questions, mine would be about the version of Ubuntu you are using, of the compiler and .. hm ... whatever comes to mind, really.

I just compiled the master branch of BALL on Debian 8. Except for an issue with the documentation, which one can fix manually, it worked just fine.

**Comment by dstoeckel** [comment]
I'll go ahead and close this, as the current master branch compiles just fine on our Ubuntu 14.04 machines here.
