### ISSUE TITLE
removal of insertion codes

### ISSUE THREAD

**Issue by smoe** [BALL-Project/ball#544]
Hello,

This report is about handling insertion codes, a not so well known feature of e.g. PDB ATOM lines and BALL should make some noise about interpreting them properly - not like OpenBABEL which fails to distinguish consecutive residues of the same type that differ only in their insertion code.

I stated it as "removal" when technically it is a specification as a blank. And BALL is perfectly right, technically, by only allowing characters to be passed and that those shall be proper characters. So, to unset an insertion code, the invocation is with a blank:
<pre>
setInsertionCode(' ');
</pre>
My initial attempt was with an empty string, though but
<pre>
setInsertionCode("");
</pre>
cannot be casted from the char* to char, obviously. It just was so intuitive. This is somewhat unfortunate, especially so from Python, where single quotes may also be used strings and a mere '' is possible, not like in C++ where '' provokes an "empty character" error. One gets confused. Out of mere curiosity, I also tried
<pre>
setInsertionCode(0);
</pre>
which is pretty darn close to an empty string. Funnily, though, this truly inserts a 0 into the ATOM lines and thus does not show the coordinates any more when printed. 

I happily prepare a patch if there are instructions from your side how you want it - if you want it. Please have the Python interface in mind for whatever you plan about it.

**Comment by dstoeckel** [comment]
Oops, I suppose this is my fault... I prepared a patch that essentially validates whether the passed character is visible and throws an InvalidArgument exception if not. Additionally it introduces a convenience method `unsetInsertionCode()` that just calls `setInsertionCode(' ')`.

Would that be a solution that is acceptable from a Python point of view?

**Comment by smoe** [comment]
Ha! Thank you for the unsetI..C.. routine - nice!   I am not sure how exactly the insertion code is defined. If it is A-Z then passing the number 0 should be the blank and 1 be substituted with 'A'. If the type ACHAR is A-Z0-9 then I lose the confidence in this suggestion. For Python I presume you just want to accept the empty string and leave everything else as it is.

**Comment by dstoeckel** [comment]
From the PDB documentation:

> Alphabet letters are commonly used for insertion code. [...]

And the definition of aChar:

> An alphabetic character (A-Z, a-z).

The problem here is just that I do not want the PDB parser to bail out because someone used a non-standard insertion code. (Refusing to _write_ such an insertion code is a different story though...).

I doubt that magically turning numerical input into a character is more user friendly than documenting, that the function accepts every visible character + ' ' and throwing an exception. The proper solution would be to define an enum with entries for every valid insertion code.
This however would cover almost all ASCII characters in our case and complicate the parser code unnecessarily.

So while I am not entirely happy with runtime checking the insertion code character, it is probably the simplest solution.

**Comment by smoe** [comment]
Makes all good sense to me. Your pointer to the unsetInsertionCode routine basically closed this issue already. That particular routine has yet not migrated to the python interface, has it? I just cross-checked, it does not seem to be around.

Something related: The print routine does not show the insertion code - which it should:
<pre>

In [37]: r=p.getResidue(30)

In [38]: r.getInsertionCode()
Out[38]: 'A'

In [39]: print r
Residue SER30 { 11 atoms }

In [40]: r=p.getResidue(29)

In [41]: r.getInsertionCode()
Out[41]: ' '

In [42]: print r
Residue SER30 { 11 atoms }

</pre>

I admit that this is some kind of patch that I could provide - tell me so if you like pull requests :)

**Comment by dstoeckel** [comment]
I pushed the patch just now. The unsetInsertionCode should be wrapped for Python.
