### ISSUE TITLE
Build error on windows : incorrect path for flex, bison and moc.

### ISSUE THREAD

**Issue by Laura-K** [BALL-Project/ball#547]
Hello

I can't compile BALL on windows.

First, BISON and FLEX can't find the *Lexer.l files and the *Parser.y files. It seems that it can be partially corrected by remplacing the two lines : 
	SET(PARSERINPUT ${DIRECTORY}/${BASENAME}Parser.y)
	SET(LEXERINPUT ${DIRECTORY}/${BASENAME}Lexer.l)
by
	SET(PARSERINPUT ${PROJECT_SOURCE_DIR}/${DIRECTORY}/${BASENAME}Parser.y)
	SET(LEXERINPUT ${PROJECT_SOURCE_DIR}/${DIRECTORY}/${BASENAME}Lexer.l)
in BALLMacros.cmake lines 102 and 103. But sometimes one lexer file is still missing (GAMESSDatParserLexer.C in my case).

Plus, moc don't find the files for the generation of source/SYSTEM/moc_simpleDownloader.C : 
2>  Generating source/SYSTEM/moc_simpleDownloader.C
2>  The system cannot find the path specified.
2>  moc: Cannot open options file specified with @

Regards,

Laura K

**Comment by Laura-K** [comment]
Hi,
The problem cames from CMake, it's a bug present in the 2.8 version. It has been resolved in the 2.8.3 as you can see in their bug tracker https://public.kitware.com/Bug/view.php?id=11120 .
Since I use CMake 2.8.3, FLEX, BISON and MOC find their respectives files.

Your installation tutorial https://github.com/BALL-Project/ball/wiki/DevelopmentEnvironment should advise to use 2.8.3 instead ;)

Regards,

Laura K

**Comment by dstoeckel** [comment]
Thank you for finding this out. I updated the page accordingly.
