### ISSUE TITLE
How can I translate/rotate a molecule in BALL

### ISSUE THREAD

**Issue by smoe** [BALL-Project/ball#555]
Hello,

We are generating a trimeric protein over here and need to twist, move and turn what the PeptideBuilder brings us. Can you please suggest respective methods in BALL?  I found the vector3 class and have seen the += operator, but this has not found its way up the aggregation to the atomContainer or the Molecule. We plan to determine an axis along which to rotate, but rotation is not even seen in the vector3 or plane3 class. Should we look further in the VIEW API? Or implement something along those lines in BALL?

Best,

Steffen

**Comment by pbrach** [comment]
Hello Steffen,

If I am not mistaken you will need: BALL/STRUCTURE/geometricTransformations.h. Here you find the BALL::TransformationProcessor which allows you to apply a 4x4 Transformation Matrix to any AtomContainer. This can be done using the BALL-"apply"-syntax with all Classes that inherit from BALL::UnaryProcessor. There are further tools that reduce the problem to basically defining a rotation axis and an angle and then give you the necessary Matrix, which in turn can then be fed to the BALL::TransformationProcessor...

Does this help? If so you do you need further instructions?
Best,
Phil

**Comment by dstoeckel** [comment]
Hi,
there is a class RotateBond (`#include <BALL/DOCKING/GENETICDOCK/rotateBond.h>`) that may do what you want. Generally rotating around a specific bond can be tricky when there are cyclic protein topologies, which is why there is no general "rotate" method in BALL. If you want to rotate an arbitrary set of atoms around an arbitrary axis you can use the `Matrix4x4::setRotationMethod` and simply do something like this:

```c++
Matrix4x4 toCenter, rotation, fromCenter;
// Center the set of atoms at the origin
toCenter.translate(-cog);
// Rotate the atoms
rotation.setRotation(angle, axis);
// Move them back to their original position
fromCenter.translate(cog);

// Build a composite transformation
rotation = fromCenter * rotation * toCenter;

// Rotate all atoms
for(auto& atom : container.atoms()) {
  atom.setPosition(matrix * atom.getPositon())
}
```

Doing a quick grep over the code, the RotateBond functionality seems to be replicated at way too many places though...

**Comment by pbrach** [comment]
Yeah: the interface for rotating molecules is somewhat not so super obvious and generally implemented if you ask me. I have to admit that I added a further method to just rotate around a bond about an arbirary angle very similar to BALL/STRUCTURE/geometricProperties.h and here the function:

bool setTorsionAngle(const Atom& a1, const Atom& a2, Atom& a3, const Atom& a4, Angle angle)

But my variant needs only the bond... I realized the general problem with rotations is that there is a myriad of different ways of how you want to rotate and what should define your axis. So basically it is quite okay to have the the general methods. 

@smoe : To have an example of how to apply any rotation, please checkout the above mentioned setTorsionAngle function

**Comment by smoe** [comment]
Thank you both for your intriguing comments. Someone of yours obviously read about design patterns - I am huge fan of your abstraction to processors now, so thank you for your nose-dip. So, to help those  who approach BALL from the Python side, to move the whole protein such that CA ends up at (0,0,0):
<pre>
In [122]: v=q.getChain(0).getResidue(0).getAtom("CA").getPosition()
In [123]: tlp=TranslationProcessor(Vector3(0,0,0)-v)
In [124]: q.apply(tlp)
Out[124]: True
</pre>
Testing:
<pre>
In [128]: print q.getChain(0).getResidue(0).getAtom("CA").getPosition()
(0.000000 0.000000 0.000000)
</pre>
The "Vector3(0,0,0)-v" is temporarily disturbing, hoping for a respective discussion in issue https://github.com/BALL-Project/ball/issues/556 . Otherwise I tend to think that something like this should possibly find entry into your list of sniplets in the BALL wiki.

Best,

Steffen

**Comment by smoe** [comment]
For rotation, I now came up with the following, basically continuing from the example above that has the first residue's Calpha already at the origin. Now the challenge shall be to also have the last residue - not at the origin but at least directly on the X axis.
<pre>
m=Matrix4x4()
atom=q.getChain(0).getResidue(q.getChain(0).countResidues()-1).getAtom("CA")
angle=atom.getPosition().getAngle(Vector3(1,0,0))
rotationAxis=atom.getPosition() % Vector3(1,0,0)
m.setRotation(angle,rotationAxis)
tfp=TransformationProcessor(m)
q.apply(tfp)
</pre>
Testing - there is (mostly) no deviation towards the Y or Z axes, so we are directly on X:
<pre>
In [233]: print atom.getPosition()
(79.628944 0.000013 -0.000000)
</pre>
What can I say - I liked it.  Thanks again, and make some noise about how nicely (and consistently!) BALL can twist, move and rotate.

Steffen
