### ISSUE TITLE
Does the Class AtomContainer have the method "apply"?

### ISSUE THREAD

**Issue by autodataming** [BALL-Project/ball#565]
I read some code in the ligsite http://projects.biotec.tu-dresden.de/pocket/
Vector3 doPreTranslation(AtomContainer&  atom_container )
{
  Vector3 mc = getMassCenter( atom_container );
	TranslationProcessor tp( -mc );
	atom_container.apply( tp );
	return mc;
  
}
but I can't find the method 'apply'

**Comment by pbrach** [comment]
Hey there!

well BALL::AtomContainer inherits from BALL::Composite and BALL::PropertyManager. The method `apply()` originates from **BALL::Composite**. In the code example you've given the unary operator `tp` will be applied to every atom in the BALL::AtomContainer `atom_container`.

A bit of an explanation how this works:
Atoms are assoziated or composed (not sure there) with a AtomContainer as a list of Composites.... this basically means the TranslationProcessor is applied to every Atom item in that list.

best,
Phil

**Comment by autodataming** [comment]
thankyou
