### ISSUE TITLE
boost_system-vc100-mt-gd-1_47.lib  AND    boost_system-vc100-mt-1_47.lib

### ISSUE THREAD

**Issue by autodataming** [BALL-Project/ball#567]
When I use debug mode to compile BALL, it need boost_system-vc100-mt-gd-1_47.lib .
But in the contrib you offfer[Pre-built contrib binaries for Win32/VS2010], it just have boost_system-vc100-mt-1_47.lib.

can you offer boost_system-vc100-mt-gd-1_47.lib to me?

**Comment by philthiel** [comment]
Dear colleague,
not totally sure but I think that the pre-build contrib binaries for Windows are only release builds.
Best,
Philipp

**Comment by autodataming** [comment]
I got it. Thank you.
