### ISSUE TITLE
what's the relationship between vector3.h and vector4.h?

### ISSUE THREAD

**Issue by autodataming** [BALL-Project/ball#569]
I read some code:

``` C++
-----
 #include <BALL/MATHS/vector4.h>
Vector3  orgin=(0.,0.,0.);
--------------
```

why not include vector3.h?

**Comment by philthiel** [comment]
Where have you found these lines (hard to answer out of the context)? I don't think that there's a special relationship. The include of vector3.h most likely occurs in another place.
