### ISSUE TITLE
Parameter file not found when using default settings for Bond Order Assignment in BALLView

### ISSUE THREAD

**Issue by cschaerfe** [BALL-Project/ball#571]
When assigning bond orders in BALLView a panel pops up where the user should define a file 
for "Atomic Valence Penalty Rules" with default path "bond_lengths/BondOrder.xml". That file indeed exists.
Upon clicking "OK", the following error is logged:

```
  >   > assigning bond orders ...
The given parameter file does not exist! Using default!
```

Which is somewhat contradicting the fact that we were using default settings from the beginning.

Additional Note:
For some reason  BALLView freezes when running the same operation after calculating H-bonds.

**Comment by philthiel** [comment]
Fixed by 6ed4a08602f001f6f6c93fe350e63d6a0b4c1887
