### ISSUE TITLE
Make fails at BALLView

### ISSUE THREAD

**Issue by Garonmonk** [BALL-Project/ball#598]
Hi,
I'm trying to install BALL in my computer. CMake went well, but when it comes to Make, it appears the following error:

[ 71%] Linking CXX executable ../../../bin/BALLView
CMakeFiles/BALLView.dir/demoTutorialDialog.o:(.qtversion[qt_version_tag]+0x0): undefined reference to `qt_version_tag'
collect2: error: ld returned 1 exit status
source/APPLICATIONS/BALLVIEW/CMakeFiles/BALLView.dir/build.make:270: recipe for target 'bin/BALLView' failed
make[2]: *** [bin/BALLView] Error 1
CMakeFiles/Makefile2:1384: recipe for target 'source/APPLICATIONS/BALLVIEW/CMakeFiles/BALLView.dir/all' failed
make[1]: *** [source/APPLICATIONS/BALLVIEW/CMakeFiles/BALLView.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

I'm quite new into this, and after searching around I couldn't get any proper answer.
Does anyone know how to fix this mistake?

Thanks.

**Comment by philthiel** [comment]
Hey,

welcome to BALL!

Can you give us some more information on your setup:
- Your OS?
- Compiler (version)?
- What source code do you use (GitHub clone)?
- Do you use the contrib of BALL?
- Your Qt version?

Best,
Philipp

**Comment by Garonmonk** [comment]
Hi there,

My OS is Ubuntu 16.04.
My compiler version is gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)
The GitHub clone may it be qt5_latest? I was just following the instructions here http://www.ball-project.org/installation/linux/. Never work with Git before.
I've been using the contrib of BALL, actually it is well installed (cmake .. and make afterwards, at it says in the link mentioned above)
Qt version is 5.5.

I hope I've given the proper information. Thanks for the help, and apologies for any inconvenience.

Regards,
Eric

**Comment by philthiel** [comment]
Hi Eric,

oh, I see. Could you please try to do the following:

1. Cleanup your 'build' directory
2. Checkout the master branch as follows:   $ git checkout master
3. Call again cmake and make

However, I have to mention that BALLView will most likely not work,
as the current development (master) branch needs to be fixed.

If you don't need the View components (BALLView + lib) you can speedup the build by adding the following flag to your cmake call: -DBALL_HAS_VIEW=OFF

If you need BALLView, you should try to compile the latest stable [BALL release 1.4.2](https://abibuilder.informatik.uni-tuebingen.de/archive/ball/BALL/stable/v1.4.2/BALL-1.4.2.tar.bz2) and the corresponding [Contrib](https://abibuilder.informatik.uni-tuebingen.de/archive/ball/contrib/v1.4.2/contrib-1.4.2.tar.gz). The old contrib isn't cmake based but offers an autobuild script.

Best,
Philipp

**Comment by Garonmonk** [comment]
Hi Philipp,

I've done what you told me, cleaned up the build directory and made a new one, did again cmake and make ( cmake .. -DBALL_CONTRIB_PATH=/home/eric/Documents/Software/ball_contrib-master/build/install -DCMAKE_PREFIX_PATH=/home/eric/Documents/Software/Qt/5.5/gcc_64/lib/cmake -DBALL_HAS_VIEW=OFF), but now a new error appears:

[ 57%] Building CXX object source/APPLICATIONS/TOOLS/CMakeFiles/MolDepict.dir/MolDepict_automoc.o
[ 57%] Linking CXX executable ../../../bin/TOOLS/MolDepict
CMakeFiles/MolDepict.dir/MolDepict.o:(.qtversion[qt_version_tag]+0x0): undefined reference to `qt_version_tag'
collect2: error: ld returned 1 exit status
source/APPLICATIONS/TOOLS/CMakeFiles/MolDepict.dir/build.make:140: recipe for target 'bin/TOOLS/MolDepict' failed
make[2]: *** [bin/TOOLS/MolDepict] Error 1
CMakeFiles/Makefile2:1363: recipe for target 'source/APPLICATIONS/TOOLS/CMakeFiles/MolDepict.dir/all' failed
make[1]: *** [source/APPLICATIONS/TOOLS/CMakeFiles/MolDepict.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Regarding git checkout master, the output is the following:

fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

It seems I'm not using well the repo lol.
And I don't really need BALLView so as long as I can keep working without it is Ok.

Thanks again for your help,
Eric

**Comment by philthiel** [comment]
Ok, let's go through it step by step ; )

Regarding 'git checkout master': please try to execute this command in the root directory of your   BALL source code. A message like _Switched to a new branch 'master'_ should appear. If so, please cleanup the build directory, call cmake and make again.

Btw: have you build Qt5.5 separately from the contrib?

**Comment by Garonmonk** [comment]
Cool, I'm just downloading again BALL from git (git clone https://github.com/BALL-Project/ball.git) just in case.

Yes, I've built Qt5.5 separately, but I think that if I specify the proper path will still work, isn't it?

**Comment by Garonmonk** [comment]
Still the same error message:
[ 57%] Linking CXX executable ../../../bin/TOOLS/MolDepict
CMakeFiles/MolDepict.dir/MolDepict.o:(.qtversion[qt_version_tag]+0x0): undefined reference to `qt_version_tag'
collect2: error: ld returned 1 exit status
source/APPLICATIONS/TOOLS/CMakeFiles/MolDepict.dir/build.make:140: recipe for target 'bin/TOOLS/MolDepict' failed
make[2]: *** [bin/TOOLS/MolDepict] Error 1
CMakeFiles/Makefile2:1363: recipe for target 'source/APPLICATIONS/TOOLS/CMakeFiles/MolDepict.dir/all' failed
make[1]: *** [source/APPLICATIONS/TOOLS/CMakeFiles/MolDepict.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by philthiel** [comment]
Hm, let's try to get rid of the failing tool (most likely you don't need this one). 
Could you please open the file: 
<ball_root>/source/APPLICATIONS/TOOLS/sources.cmake 
 and comment out line 71 to be read as follows: 
#MolDepict
Finally, run make again.

**Comment by Garonmonk** [comment]
On it, I was just reinstalling also the ball_contrib from, just in case. I let you know when I'm back to the make step of BALL.

**Comment by Garonmonk** [comment]
ok, now this error:
[ 65%] Building CXX object source/APPLICATIONS/TOOLS/CMakeFiles/Ligand3DGenerator.dir/Ligand3DGenerator_automoc.o
[ 65%] Linking CXX executable ../../../bin/TOOLS/Ligand3DGenerator
CMakeFiles/Ligand3DGenerator.dir/Ligand3DGenerator.o:(.qtversion[qt_version_tag]+0x0): undefined reference to `qt_version_tag'
collect2: error: ld returned 1 exit status
source/APPLICATIONS/TOOLS/CMakeFiles/Ligand3DGenerator.dir/build.make:140: recipe for target 'bin/TOOLS/Ligand3DGenerator' failed
make[2]: *** [bin/TOOLS/Ligand3DGenerator] Error 1
CMakeFiles/Makefile2:1360: recipe for target 'source/APPLICATIONS/TOOLS/CMakeFiles/Ligand3DGenerator.dir/all' failed
make[1]: *** [source/APPLICATIONS/TOOLS/CMakeFiles/Ligand3DGenerator.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by philthiel** [comment]
No!
Then you should try a last cmake flag: -DBALL_BUILD_TOOLS=OFF
This skips all tools and you should be fine!!

**Comment by Garonmonk** [comment]
Ok, done it! Everything is fine now!
Thank you very much.

**Comment by philthiel** [comment]
You're welcome, have fun!
