### ISSUE TITLE
Splash screen hides data path selection dialog (macOS)

### ISSUE THREAD

**Issue by tkemmer** [BALL-Project/ball#604]
On macOS, the BALLView splash screen is shown on top of the data path selection dialog (in case of a missing or invalid `BALL_DATA_PATH`). With display resolutions below WQHD, this can be quite annoying, as there is no sufficient space left where the dialog could be shown completely.

**Comment by tkemmer** [comment]
Upstream bug https://bugreports.qt.io/browse/QTBUG-35169.

**Comment by philthiel** [comment]
Splashscreen has been removed (a7a3a0fd21febf61f48e7871d40f6245c102a1c3).
