### ISSUE TITLE
Using BALL externally requires explicit find_package(Qt5 Core Xml Network)

### ISSUE THREAD

**Issue by tkemmer** [BALL-Project/ball#611]
Using the BALL library [in external projects via CMake](https://github.com/BALL-Project/ball/wiki/UsingCMakeExternally) requires explicitly importing Qt5Core, Qt5Xml, and Qt5Network:

```
-- Configuring done
CMake Error at CMakeLists.txt:13 (ADD_EXECUTABLE):
  Target "foo" links to target "Qt5::Core" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:13 (ADD_EXECUTABLE):
  Target "foo" links to target "Qt5::Xml" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:13 (ADD_EXECUTABLE):
  Target "foo" links to target "Qt5::Network" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

**Comment by philthiel** [comment]
Hi Thomas,

can you please test the following branch: pt/cmake_package_config

BALL's package configuration files will now take care of the required BALL dependencies.
However, if BALL dependencies are placed in non-standard locations (e.g. like for ball_contrib) the consuming project has to specify the path(s) using -DCMAKE_PREFIX_PATH. 

I have update the wiki entry accordingly.

Best,
Philipp

**Comment by tkemmer** [comment]
Works for me, thanks!

> However, if *BALL dependencies* are placed in non-standard locations[...]

Hmm, but this should only affect Qt5 as all of the other dependencies are exported via their absolute paths. I guess `find_dependency` does not forward the original prefix paths as well. Should we consider this working-as-intended?

**Comment by philthiel** [comment]
Fine with me, builds on all test setups. Changes merged
