### ISSUE TITLE
BALLView crashing due to missing OpenGL context (Win10)

### ISSUE THREAD

**Issue by tkemmer** [BALL-Project/ball#612]
BALLView currently refuses to start on our Windows 10 test machine. At first glance, there seemed to be a nesting error in the display list handler (`NestedDisplayList` error), but the actual problem turned out to be a missing OpenGL context when creating the `Scene`.

While investigating the problem, I replaced the misleading exception (395deb5cd0efdda0807e5a0ab93eb94a88f8499f). Still not quite sure what has changed as compared to our previous (working) setup.

@philthiel: Would it be possible to add a minimalistic BALLView runtime test to our CI workflow (like running BALLView once and watching for exceptions)? Most of the OpenGL-related stuff happens at runtime and sneaks through our current tests.

**Comment by philthiel** [comment]
Good idea, I will add a BALLView startup test.
(However, on our Win 10 build machine BALLView starts.)

**Comment by tkemmer** [comment]
Hmm, nevermind. The graphics driver on our machine seems to be *completely* broken and several other apps are affected as well. This does not seem to be BALL related.
