### ISSUE TITLE
Have Ball-Project implemented LIGSITE Algorithm?

### ISSUE THREAD

**Issue by ludlows** [BALL-Project/ball#613]
Dear friends,

I am doing research on map binding site to vector.
But I need to detect it at first.
So I decide to use LIGSITE to do it in Ball-Project.
Have you implemented it in this repository?

Thank you!

**Comment by philthiel** [comment]
Dear WangMiao,

no, we haven't implemented LIGSITE.
BALL currently offers the PASS algorithm for pocket detection implemented in BALL/bindingPocketProcessor.h ( Caetano Traina, et al, 2000: Fast Feature Selection Using Fractal Dimension). 

Best,
Philipp

**Comment by ludlows** [comment]
Thank U, Philipp.
Another question: Can I call Ball code from Python?

**Comment by philthiel** [comment]
Yes you can. 
Build BALL with Python support (default if Python devel and SIP can be found).
Have a look here: http://www.ball-project.org/installation/
You will find OS specific build and setup instructions!

**Comment by ludlows** [comment]
Thank you for your warm response!

**Comment by philthiel** [comment]
You're welcome!

Btw, we have a mailing list that you can use for questions ; )
https://groups.google.com/forum/#!forum/ball-user-list
