### ISSUE TITLE
BALLView segfaults on double clicking an empty scene on Windows

### ISSUE THREAD

**Issue by tkemmer** [BALL-Project/ball#620]
Steps to reproduce:
 * Open new BALLView instance with no structures loaded
 * Double click somewhere in the scene widget

**Comment by philthiel** [comment]
Additional observation: 
- this only happens if RTfact is the selected rendering method.
- OpenGL rendering is stable for this action

**Comment by philthiel** [comment]
Btw.: It seems that RTfact is the default rendering method if available. 
I would propose to change that because this can lead to unexpected long delays 
when downloading a structure and generating the initial visualization.

**Comment by tkemmer** [comment]
Yeah, agreed.

**Comment by philthiel** [comment]
- segfault happens here:

https://github.com/BALL-Project/ball/blob/master/source/VIEW/RENDERING/RENDERERS/rtfactRenderer.C#L95

- _renderBuffer_ handle is NULL
- we have to check where _renderBuffer_ should be initialized
