### ISSUE TITLE
Counting molecules in PDBFile 

### ISSUE THREAD

**Issue by jeleclaire** [BALL-Project/ball#629]
I created two simple water molecules and put them in a system. When calling system's countMolecules(), it returns the correct number. Then, the system is written to a pdb file. After reopening the pdb and reading the contents to a system, system's countMolecules() returns only one molecule (containing all six atoms of the two water molecules).
I tried another data format (HIN file)  and in this case, it returns the correct number.  I am not sure, if the pdb file simply needs more information about the molecules (maybe the different molecules have to be declared in the title section?).  Basic steps are given below.
```C++
// CREATION OF WATER MOLECULES
System S; 
// fill system with two water molecules 
Molecule m1;
Atom o (PTE[Element::O], "O");
Atom h1 (PTE[Element::H], "H");
Atom h2(PTE[Element::H], "H");
o.createBond(h1);
o.createBond(h2);
m1.insert(o);
m1.insert(h1);
m1.insert(h2);
S.insert(m1);


Molecule m2(m1, true); //create a deep copy of m1
//translate and rotate molecule 2 such that the two molecules are not overlapping
// function uses BALL's Transformationprocessor
transformMolecule(m2);
S.insert(m2);

std::cout << "BEFORE writing, s contains:  " << S.countMolecules() << "\n;
//outputs 2


// WRITING
PDBFile outfile(output_name, ios::out);
outfile << S; 
outfile.close();

//READING
PDBFile infile(input_name); 
System s; 
f >> s;	 
std::cout << "AFTER writing, s contains:  " << s.countMolecules() << "\n;
//outputs 1 
```

**Comment by philthiel** [comment]
PDB files are very special. What you should do is to use BALL::Residue instead of BALL::Molecule to create the waters. Residues then have to be inserted into chains, chains into proteins, and ... proteins into systems : ) This is how PDB-ready systems are constructed. 

If you then call countResidues() on the system, e.g., the result is as you expect it!
Please find a possible snippet in the following:

```C++
// Create residues and populate
Residue r1;
r1.setName("HOH");
PDBAtom o (PTE[Element::O], "O");
PDBAtom h1 (PTE[Element::H], "H");
PDBAtom h2(PTE[Element::H], "H");
o.createBond(h1);
o.createBond(h2);
r1.insert(o);
r1.insert(h1);
r1.insert(h2);

Residue r2(r1, true); //create a deep copy of m1

// Create chain and populate
Chain *c = new Chain("A");
c->insert(r1);
c->insert(r2);

// Create protein and populate
Protein* p = new Protein("TESTLE");
p->insert(*c);

// Create system and populate
System S;
S.insert(*p);
```

**Comment by jeleclaire** [comment]
Ok, I agree. This is not an issue but rather misleading. 

Of course, this one can be closed.
