### ISSUE TITLE
Model gets invisible when setting transparency

### ISSUE THREAD

**Issue by philthiel** [BALL-Project/ball#638]
- Tested on macOS and Windows.
- Master branch 
- Current commit: 8f71dd4e1210c9140d5a4259595edbcdc0314ea6

Replication in BALLView: 
- Load or generate a structure
- In the _Modify Model_ dialog, section _Coloring_ set transparency to any value != 0
- The model vanishes in the scene.

**Comment by tkemmer** [comment]
Also confirmed on Linux.

**Comment by tkemmer** [comment]
When introducing explicit type conversions to the following line
https://github.com/BALL-Project/ball/blob/ecd8330ef86ad576f50b8499dca363659abc03ec/include/BALL/VIEW/RENDERING/RENDERERS/glRenderer.iC#L115
transparency seems to work again. Well, until you move the camera, that is. As soon as the camera position changes, the whole model disappears until transparency is set to 0 again or  BALLView is restarted.
