### ISSUE TITLE
CMake Error in step: make 

### ISSUE THREAD

**Issue by 00aixxia00** [BALL-Project/ball#641]
CMakeFiles/BALL.dir/source/STRUCTURE/solventExcludedSurface.C.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:490: CMakeFiles/BALL.dir/all] Fehler 2
make: *** [Makefile:141: all] Fehler 2

I'm using Arch Linux. 

I'd be very thankfull for help.

**Comment by tkemmer** [comment]
Please provide the whole error message (including a bit of context). How did you configure BALL? Any additional parameters to the cmake command?

**Comment by philthiel** [comment]
This issue has been relocated to the ball_contrib repository.
