### ISSUE TITLE
Problem top5 count runs

### ISSUE THREAD

**Issue by pglandrew** [BALL-Project/ball#643]
Hello i have this problem with my bcp, he dont count my games on top 5 run! what i mean? he dont count bot runs...if i do manual runs...he count but if i do with bot runs he dont count in top5 

i'm not a scripter, i know little edit, so what i understand from bcp script he save the games on top5

if the player or bot using SaveExit, on the bot i dont use SaveExit, i use quitGame that means exist instant, any ideea how to fix this in bcp script please?

need to add the quitGame to save runs, for manual players who do runs and for bots also need to work for both of them, so for manual player SaveExit working already, need for bots quitGame!

Regards

**Comment by tkemmer** [comment]
Heya, I'm afraid you're confusing repositories here. This project is not - in any way - related to the BCP project you're referring to.
