### ISSUE TITLE
PDB download not working.

### ISSUE THREAD

**Issue by ahwchemistry** [BALL-Project/ball#644]
Downloading 5ebv results in the following message.

Url: http://www.rcsb.org/pdb/files/5ebv.pdb1.gz
Could not download PDBFile! Reason given was "Error transferring http://www.rcsb.org/pdb/files/5ebv.pdb1.gz - server replied: Not Found"

**Comment by philthiel** [comment]
Hi,
could you please tell us what BALL version you used and what kind of installation?

**Comment by ahwchemistry** [comment]
Hello,

I was using ball view 1.5.0 and 1.4.79 on Windows 10

Sincerely,

Alex Williams

**Comment by philthiel** [comment]
Hi Alex,

can you please try to delete the .BALLView file -- if present -- that is located in your user home directory? Then please try again with the 1.5.0 BALLView installation.

Best,
Philipp
