### ISSUE TITLE
Project website wrong redirect

### ISSUE THREAD

**Issue by hansioan** [BALL-Project/ball#656]
I found your website initially at the location
http://www.ball-project.org/ballaxy
which wrongly redirects to
https://ball-project.orgballaxy/
where it's missing a "/" and it should be
https://ball-project.org/ballaxy/

**Comment by philthiel** [comment]
Hi, 

from where exactly have you reached this wrong link?

Best,
Philipp

**Comment by hansioan** [comment]
Hi,

I initially got it from:
https://bio.tools/ballaxy
but I've updated the link there.
(Note: you can request ownership of the entry and improve the annotations at the above link)

However the old wrong link is still the same at:
http://www.mybiosoftware.com/ballaxy-galaxy-based-workflow-toolkit-for-structural-bioinformatics.html

**Comment by philthiel** [comment]
Thanks a lot! Problem solved.
