### ISSUE TITLE
Problems with initialising the BALL random number generators

### ISSUE THREAD

**Issue by anhi** [BALL-Project/ball#98]
**Reported by dstoeckel on 26 Nov 38777280 01:20 UTC**
When initialising the BALL RNG with larger numbers (such as time(NULL)) these get silently set to
default values, as the generating algorithm otherwise could not handle the input. Temporary
workaround: Replace the conditional in the constructor by a simple modulo operation.
Long term solution: Replace the outdated code with something better like the GSL rngs

**Comment by anhi** [comment]
**Commented by dstoeckel on 9 Aug 39487019 04:00 UTC**
Added a warning to the setup routine, however as we should consider to add better RNGs in the future I am leaving this bug open as a reminder.

**Comment by anhi** [comment]
**Commented by akdehof on 5 Feb 40936096 07:57 UTC**
Deferred to 1.4.1

**Comment by anhi** [comment]
**Commented by dstoeckel on 2 Oct 41152378 00:23 UTC**
Not necessary for 1.4.1. Removing milestone.

**Comment by anhi** [comment]
**Commented by dstoeckel on 15 Mar 43144346 18:16 UTC**
Discuss deleteion for 1.5

**Comment by anhi** [comment]
**Commented by dstoeckel on 26 Nov 43145556 23:43 UTC**
The RandomNumberGenerator is now marked as deprecated.

**Comment by anhi** [comment]
**Commented by oliver on 27 Mar 44028776 21:50 UTC**
ANd what should it be replaced with?

**Comment by tkemmer** [comment]
BALL RNG will be removed with a1bb48a1b46098411ac1aa294565d9e49d6f8845.
